using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

var options = GeneratorOptions.Parse(args);
var outputRoot = options.ResolvedOutputDirectory;
var enumPath = Path.Combine(outputRoot, "LucideKind.cs");
var dataPath = Path.Combine(outputRoot, "Data", "LucideIconData.cs");

Console.WriteLine("LucideSharp Icon Generator");
Console.WriteLine($"Repository : {options.Repository}");
Console.WriteLine($"Branch     : {options.Branch}");
Console.WriteLine($"Output     : {outputRoot}");
Console.WriteLine();

using var http = new HttpClient();
http.DefaultRequestHeaders.UserAgent.ParseAdd("LucideSharp-IconGenerator/1.0");
http.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/vnd.github+json"));
http.Timeout = TimeSpan.FromMinutes(10);

Console.WriteLine("Fetching icon list from GitHub...");
var iconFiles = await GetIconFilesAsync(http, options.Repository, options.Branch);
Console.WriteLine($"Found {iconFiles.Count} SVG icons.");

Directory.CreateDirectory(Path.GetDirectoryName(dataPath)!);

var usedEnumNames = new HashSet<string>(StringComparer.Ordinal);
var icons = new List<GeneratedIcon>(iconFiles.Count);

var downloadParallelism = Math.Clamp(Environment.ProcessorCount, 4, 16);
await Parallel.ForEachAsync(
    iconFiles,
    new ParallelOptions { MaxDegreeOfParallelism = downloadParallelism },
    async (file, cancellationToken) =>
    {
        var svg = await DownloadSvgAsync(http, options.Repository, options.Branch, file, cancellationToken);
        var enumName = ToEnumName(file, usedEnumNames);
        lock (icons)
        {
            icons.Add(new GeneratedIcon(file, enumName, svg));
        }
    });

icons.Sort(static (left, right) => string.Compare(left.FileName, right.FileName, StringComparison.Ordinal));

Console.WriteLine("Writing generated source files...");
await File.WriteAllTextAsync(enumPath, BuildEnumSource(icons), Encoding.UTF8);
await File.WriteAllTextAsync(dataPath, BuildDataSource(icons), Encoding.UTF8);

Console.WriteLine();
Console.WriteLine($"Generated {icons.Count} icons.");
Console.WriteLine($"  {enumPath}");
Console.WriteLine($"  {dataPath}");
Console.WriteLine("Done.");

static async Task<IReadOnlyList<string>> GetIconFilesAsync(HttpClient http, string repository, string branch)
{
    var treeUrl = $"https://api.github.com/repos/{repository}/git/trees/{branch}?recursive=1";
    using var response = await http.GetAsync(treeUrl);
    response.EnsureSuccessStatusCode();

    await using var stream = await response.Content.ReadAsStreamAsync();
    using var document = await JsonDocument.ParseAsync(stream);
    var tree = document.RootElement.GetProperty("tree");

    var icons = new List<string>();
    foreach (var node in tree.EnumerateArray())
    {
        if (node.GetProperty("type").GetString() != "blob")
        {
            continue;
        }

        var path = node.GetProperty("path").GetString();
        if (path is null ||
            !path.StartsWith($"{GeneratorDefaults.IconsFolder}/", StringComparison.Ordinal) ||
            !path.EndsWith(".svg", StringComparison.OrdinalIgnoreCase))
        {
            continue;
        }

        icons.Add(Path.GetFileNameWithoutExtension(path));
    }

    return icons;
}

static async Task<string> DownloadSvgAsync(
    HttpClient http,
    string repository,
    string branch,
    string iconName,
    CancellationToken cancellationToken)
{
    var url = $"https://raw.githubusercontent.com/{repository}/{branch}/{GeneratorDefaults.IconsFolder}/{iconName}.svg";
    return await http.GetStringAsync(url, cancellationToken);
}

static string ToEnumName(string fileName, HashSet<string> usedNames)
{
    var parts = fileName.Split('-', StringSplitOptions.RemoveEmptyEntries);
    var builder = new StringBuilder();

    foreach (var part in parts)
    {
        if (part.Length == 0)
        {
            continue;
        }

        if (char.IsDigit(part[0]))
        {
            builder.Append('_');
        }

        builder.Append(char.ToUpperInvariant(part[0]));
        if (part.Length > 1)
        {
            builder.Append(part.AsSpan(1));
        }
    }

    var enumName = builder.Length == 0 ? "Unknown" : builder.ToString();
    if (!usedNames.Add(enumName))
    {
        var suffix = 2;
        var uniqueName = $"{enumName}_{suffix}";
        while (!usedNames.Add(uniqueName))
        {
            suffix++;
            uniqueName = $"{enumName}_{suffix}";
        }

        enumName = uniqueName;
    }

    return enumName;
}

static string BuildEnumSource(IReadOnlyList<GeneratedIcon> icons)
{
    var builder = new StringBuilder();
    builder.AppendLine("// <auto-generated />");
    builder.AppendLine($"// Generated by LucideSharp.IconGenerator on {DateTime.UtcNow:O}");
    builder.AppendLine($"// Icon count: {icons.Count}");
    builder.AppendLine();
    builder.AppendLine("namespace LucideSharp.WinForms;");
    builder.AppendLine();
    builder.AppendLine("/// <summary>");
    builder.AppendLine("/// Strongly typed access to all Lucide icons.");
    builder.AppendLine("/// </summary>");
    builder.AppendLine("public enum LucideKind");
    builder.AppendLine("{");

    for (var index = 0; index < icons.Count; index++)
    {
        var icon = icons[index];
        builder.AppendLine($"    /// <summary>{icon.FileName}</summary>");
        builder.AppendLine($"    {icon.EnumName} = {index},");
    }

    builder.AppendLine("}");
    return builder.ToString();
}

static string BuildDataSource(IReadOnlyList<GeneratedIcon> icons)
{
    var builder = new StringBuilder();
    builder.AppendLine("// <auto-generated />");
    builder.AppendLine($"// Generated by LucideSharp.IconGenerator on {DateTime.UtcNow:O}");
    builder.AppendLine($"// Icon count: {icons.Count}");
    builder.AppendLine();
    builder.AppendLine("namespace LucideSharp.WinForms;");
    builder.AppendLine();
    builder.AppendLine("/// <summary>");
    builder.AppendLine("/// Embedded Lucide SVG icon data.");
    builder.AppendLine("/// </summary>");
    builder.AppendLine("internal static class LucideIconData");
    builder.AppendLine("{");
    builder.AppendLine("    private static readonly string[] SvgData = new string[]");
    builder.AppendLine("    {");
    foreach (var icon in icons)
    {
        builder.Append("        @\"");
        builder.Append(EscapeSvg(icon.SvgContent));
        builder.AppendLine("\",");
    }

    builder.AppendLine("    };");
    builder.AppendLine();
    builder.AppendLine("    public static string GetSvg(LucideKind kind)");
    builder.AppendLine("    {");
    builder.AppendLine("        var index = (int)kind;");
    builder.AppendLine("        if ((uint)index >= (uint)SvgData.Length)");
    builder.AppendLine("        {");
    builder.AppendLine("            throw new ArgumentOutOfRangeException(nameof(kind), kind, \"Unknown Lucide icon kind.\");");
    builder.AppendLine("        }");
    builder.AppendLine();
    builder.AppendLine("        return SvgData[index];");
    builder.AppendLine("    }");
    builder.AppendLine();
    builder.AppendLine($"    public static int Count => {icons.Count};");
    builder.AppendLine("}");
    return builder.ToString();
}

static string EscapeSvg(string svg) =>
    svg.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\"\"", StringComparison.Ordinal);

internal static class GeneratorDefaults
{
    public const string DefaultRepo = "lucide-icons/lucide";
    public const string DefaultBranch = "main";
    public const string IconsFolder = "icons";
}

internal sealed record GeneratedIcon(string FileName, string EnumName, string SvgContent);

internal sealed record GeneratorOptions(
    string Repository,
    string Branch,
    string? OutputDirectory = null)
{
    public string ResolvedOutputDirectory => OutputDirectory ?? Path.GetFullPath(Path.Combine(
        AppContext.BaseDirectory,
        "..", "..", "..", "..", "..",
        "src", "LucideSharp.WinForms"));

    public static GeneratorOptions Parse(string[] args)
    {
        var repository = GeneratorDefaults.DefaultRepo;
        var branch = GeneratorDefaults.DefaultBranch;
        string? outputDirectory = null;

        for (var index = 0; index < args.Length; index++)
        {
            switch (args[index])
            {
                case "--repo" when index + 1 < args.Length:
                    repository = args[++index];
                    break;
                case "--branch" when index + 1 < args.Length:
                    branch = args[++index];
                    break;
                case "--output" when index + 1 < args.Length:
                    outputDirectory = args[++index];
                    break;
                case "--help":
                case "-h":
                    PrintHelp();
                    Environment.Exit(0);
                    break;
            }
        }

        return new GeneratorOptions(
            string.IsNullOrWhiteSpace(repository) ? GeneratorDefaults.DefaultRepo : repository,
            string.IsNullOrWhiteSpace(branch) ? GeneratorDefaults.DefaultBranch : branch,
            outputDirectory);
    }

    private static void PrintHelp()
    {
        Console.WriteLine("LucideSharp Icon Generator");
        Console.WriteLine();
        Console.WriteLine("Usage:");
        Console.WriteLine("  dotnet run --project tools/IconGenerator");
        Console.WriteLine("  dotnet run --project tools/IconGenerator -- --output <path>");
        Console.WriteLine("  dotnet run --project tools/IconGenerator -- --repo lucide-icons/lucide --branch main");
    }
}